### ISSUE TITLE
Typo in preview image of README.md

### ISSUE THREAD

**Issue by tiomno** [Trixieapp/react-virgin#14]
The text "List of all componen**e**ts used" should say "List of all components used".

Great job, keep it up!

**Comment by mccallofthewild** [comment]
Another one: "veritcal" should be "vertical"... but ditto 👆
Great project!

**Comment by SoorajChandran** [comment]
@tiomno @mccallofthewild Aww! Never noticed that. Thanks for the heads up. This will be fixed soon.

**Comment by SoorajChandran** [comment]
It's fixed in the code. The screenshot will be soon updated 🍡 . Will close the issue after that.

**Comment by pcabrera83** [comment]
I'm having issues cloning this project. I have node and npm installed.

**Comment by SoorajChandran** [comment]
@pcabrera83  Can you be a little more specific?

**Comment by SoorajChandran** [comment]
@tiomno @mccallofthewild  Screenshots has been updated 💪🏼
