### ISSUE TITLE
What's the Android ETA?

### ISSUE THREAD

**Issue by x5engine** [Trixieapp/react-virgin#15]
Hi guys,

first of all very nice work :)

and thanks for making this a nice intuitive way to find components in RN.

I am just wondering about when you'll release the Android version or support for this?

Thanks again

**Comment by SoorajChandran** [comment]
@meteorplus Android version will be out in less than 10 days.

**Comment by pranavrajs** [comment]
Need to fix the tab component. Rest of things seems to be fine
