### ISSUE TITLE
Thank you for your sharing. can you explain why you don't use TabNavigator instead of StackNavigator in this Application ?

### ISSUE THREAD

**Issue by vokhuyet** [Trixieapp/react-virgin#2]
i read your code and saw you navigate another screen every time when clicking MenuItem. It can make a stack with a lot of screens.

**Comment by deadcoder0904** [comment]
Hey just hopping into the conversation. I'm also making an app using `StackNavigator` rather than `TabNavigator` 

I'm doing this bcz in `Android`, `TabNavigator` is on the top & I want it to be in bottom for both Android & IOS. The only con right now is it has slide in animation bcz of `StackNavigator`

Not sure about Trixie

**Comment by vokhuyet** [comment]
@deadcoder0904 . what does "bcz" mean?  and with RouteConfigs in TabNavigator you can make it's in the bottom for both android and ios

**Comment by SoorajChandran** [comment]
@vokhuyet We are actually react-native newbies. Maybe we should move to TabNavigator. Right now as you pointed out each screen is being stacked on top of the previous screen. It also makes the experience weird. Will fix this soon.

**Comment by deadcoder0904** [comment]
@vokhuyet `bcz` means `because` 😂 

> with RouteConfigs in TabNavigator you can make it's in the bottom for both android and ios

& wow thanks for this. I didn't knew. 

If u don't mind me asking, can we make custom bottom tab bar too ❓

**Comment by vokhuyet** [comment]
@deadcoder0904 sure, I'm always willing to. but now, i don't have time for it :(

**Comment by deadcoder0904** [comment]
No problem. Thanks @vokhuyet 👍 

I found [half solution](https://stackoverflow.com/questions/46755743/how-to-stop-default-transition-when-using-custom-tab-bar-in-react-native-using-r)

**Comment by vokhuyet** [comment]
congratulations @deadcoder0904

**Comment by pranavrajs** [comment]
Closed via #10
