### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by deadcoder0904** [Trixieapp/react-virgin#6]
Currently the only way to use Trixie is reading the source code which is not ideal. Documentation would be helpful.

**Comment by pranavrajs** [comment]
I know it's hard. We are planning to release the documentation soon.

**Comment by SoorajChandran** [comment]
@deadcoder0904 We have a basic documentation setup now! - Check this out - https://trixieapp.github.io/Trixie-React-native-UI-kit/ 
Will be updating the documentation with all the components pretty soon.

**Comment by pranavrajs** [comment]
The correct URL : https://trixieapp.github.io/react-virgin

**Comment by deadcoder0904** [comment]
Cool thanks 👍
